### ISSUE TITLE
Test errors

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/asciidoctor-rfc#98]
@opoudjis I got errors when running RSpec tests:
```
Failures:

  1) Asciidoctor::RFC::V2::Converter processes Davies template with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/davies-template-bare-06.xml.orig.txt"))).to eq(norm(File.read("spec/examples/davies-template-bare-06.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/davies-template-bare-06.xml.orig.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:70:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:70:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  2) Asciidoctor::RFC::V2::Converter processes MIB template with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/mib-doc-template-xml-06.xml.orig.txt"))).to eq(norm(File.read("spec/examples/mib-doc-template-xml-06.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/mib-doc-template-xml-06.xml.orig.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:75:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:75:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  3) Asciidoctor::RFC::V2::Converter processes rfc1149 from Markdown with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/rfc1149.md.2.xml.txt"))).to eq(norm(File.read("spec/examples/rfc1149.md.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/rfc1149.md.2.xml.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:81:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:81:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  4) Asciidoctor::RFC::V2::Converter processes rfc2100 from Markdown with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/rfc2100.md.2.xml.txt"))).to eq(norm(File.read("spec/examples/rfc2100.md.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/rfc2100.md.2.xml.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:87:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:87:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  5) Asciidoctor::RFC::V2::Converter processes rfc3514 from Markdown with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/rfc3514.md.2.xml.txt"))).to eq(norm(File.read("spec/examples/rfc3514.md.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/rfc3514.md.2.xml.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:93:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:93:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  6) Asciidoctor::RFC::V2::Converter processes rfc5841 from Markdown with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/rfc5841.md.2.xml.txt"))).to eq(norm(File.read("spec/examples/rfc5841.md.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/rfc5841.md.2.xml.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:99:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:99:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  7) Asciidoctor::RFC::V2::Converter processes rfc748 from Markdown with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/rfc748.md.2.xml.txt"))).to eq(norm(File.read("spec/examples/rfc748.md.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/rfc748.md.2.xml.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:105:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:105:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  8) Asciidoctor::RFC::V2::Converter processes rfc7511 from Markdown with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/rfc7511.md.2.xml.txt"))).to eq(norm(File.read("spec/examples/rfc7511.md.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/rfc7511.md.2.xml.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:111:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:111:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  9) Asciidoctor::RFC::V2::Converter processes draft-ietf-core-block-xx from Kramdown with equivalent text
     Failure/Error: expect(norm(File.read("spec/examples/draft-ietf-core-block-xx.xml.orig.txt"))).to eq(norm(File.read("spec/examples/draft-ietf-core-block-xx.mkd.xml.txt")))

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - spec/examples/draft-ietf-core-block-xx.xml.orig.txt
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:117:in `read'
     # ./spec/asciidoctor/rfc/v2/text_spec.rb:117:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  10) Asciidoctor::RFC::V2::Converter processes skel from Kramdown with equivalent text
      Failure/Error: expect(File.read("spec/examples/skel.xml.orig.txt")).to eq(File.read("spec/examples/skel.mkd.xml.txt"))

      Errno::ENOENT:
        No such file or directory @ rb_sysopen - spec/examples/skel.xml.orig.txt
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:123:in `read'
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:123:in `block (2 levels) in <top (required)>'
      # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  11) Asciidoctor::RFC::V2::Converter processes stupid-s from Kramdown with equivalent text
      Failure/Error: expect(File.read("spec/examples/stupid-s.xml.orig.txt")).to eq(File.read("spec/examples/stupid-s.mkd.xml.txt"))

      Errno::ENOENT:
        No such file or directory @ rb_sysopen - spec/examples/stupid-s.xml.orig.txt
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:129:in `read'
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:129:in `block (2 levels) in <top (required)>'
      # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  12) Asciidoctor::RFC::V2::Converter processes Hoffman RFC XML v2 example with equivalent text
      Failure/Error: expect(norm(File.read("spec/examples/hoffmanv2.xml.orig.txt"))).to eq(norm(File.read("spec/examples/hoffmanv2.xml.xml.txt")))

      Errno::ENOENT:
        No such file or directory @ rb_sysopen - spec/examples/hoffmanv2.xml.orig.txt
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:134:in `read'
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:134:in `block (2 levels) in <top (required)>'
      # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  13) Asciidoctor::RFC::V2::Converter processes draft-iab-rfc-framework-bis RFC XML v2 example with equivalent text
      Failure/Error: expect(norm(File.read("spec/examples/draft-iab-rfc-framework-bis.xml.orig.txt"))).to eq(norm(File.read("spec/examples/draft-iab-rfc-framework-bis.xml.xml.txt")))

      Errno::ENOENT:
        No such file or directory @ rb_sysopen - spec/examples/draft-iab-rfc-framework-bis.xml.orig.txt
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:139:in `read'
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:139:in `block (2 levels) in <top (required)>'
      # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

  14) Asciidoctor::RFC::V2::Converter processes draft-iab-html-rfc-bis RFC XML v2 example with equivalent text
      Failure/Error: expect(norm(File.read("spec/examples/draft-iab-html-rfc-bis.xml.orig.txt"))).to eq(norm(File.read("spec/examples/draft-iab-html-rfc-bis.xml.xml.txt")))

      Errno::ENOENT:
        No such file or directory @ rb_sysopen - spec/examples/draft-iab-html-rfc-bis.xml.orig.txt
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:144:in `read'
      # ./spec/asciidoctor/rfc/v2/text_spec.rb:144:in `block (2 levels) in <top (required)>'
      # ./spec/spec_helper.rb:118:in `block (2 levels) in <top (required)>'

Finished in 15.87 seconds (files took 0.41961 seconds to load)
14 examples, 14 failures
```
The files don't exist in a repo. Should the be generated?

**Comment by andrew2net** [comment]
I found the reason. My system lacked xml2rfc.
